spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/open_payment?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true&autoReconnectForPools=true&connectTimeout=30000&socketTimeout=60000
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 10
      filter: stat
      initial-size: 10
      max-wait: 60000
      min-idle: 5
      validation-query: "select 1"
      test-on-return: false
      test-on-borrow: false
      test-while-idle: true
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      time-between-eviction-runs-millis: 50000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000

cloud:
  payment:
    transfer:
      force: 0
      throttle: 1000      