spring:
  config:
    activate:
      on-profile:
        - prod
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
      - optional:nacos:lottery-web-token-${spring.profiles.active}.yml
      - optional:nacos:lottery-share-oss-${spring.profiles.active}.yml
      - optional:nacos:lottery-auth-source-${spring.profiles.active}.yml
  cloud:
    nacos:
      username:
      password:
      config:
        server-addr:
        namespace:
      discovery:
        server-addr:
        namespace:

com:
  cloud:
    redis:
      standalone:
        address:
        password: 
        user-name: default