server:
  port: 13030
spring:
  profiles:
    active: @profileActive@
  application:
    name: lottery-payment
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy/MM/dd HH:mm:ss
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      config:
        file-extension: yaml
        refresh-enabled: true
      discovery:
        group: SPRING_CLOUD_GROUP
com:
  cloud:
    web:
      security:
        enable: true
        cached: true
        resources:
          - /adm/** | * | manager | *
    event:
      publisher:
        enable: true
      subscriber:
        enable: true
      rocket:
        ons:
          subscriber:
            group: GID_thales_payment_app

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    group: DUBBO_GROUP

mybatis:
  mapper-locations: classpath:mappers/*.xml
