spring:
  config:
    activate:
      on-profile:
        - prod
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=true
      - optional:nacos:lottery-share-oss-${spring.profiles.active}.yml?refreshEnabled=true
      - optional:nacos:lottery-share-period-${spring.profiles.active}.yml?refreshEnabled=true
  cloud:
    nacos:
      config:
        server-addr:
        namespace:
      discovery:
        server-addr:
        namespace: 
