server:
  port: 9091
  compression:
    enabled: true
    min-response-size: 4KB
spring:
  profiles:
    active: @profileActive@
  application:
    name: lottery-predict
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      config:
        file-extension: yaml
        refresh-enabled: true
      discovery:
        group: SPRING_CLOUD_GROUP
com:
  cloud:
    web:
      enable: true
      security:
        enable: true
        cached: true
        excludes: /share/**
    event:
      publisher:
        enable: true

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    group: DUBBO_GROUP

mybatis:
  mapper-locations: classpath:mappers/*.xml
