spring:
  config:
    activate:
      on-profile:
        - prod
    import:
      - nacos:lottery-web-token-${spring.profiles.active}.yml?refreshEnabled=true
      - nacos:lottery-auth-source-${spring.profiles.active}.yml?refreshEnabled=true
  cloud:
    nacos:
      config:
        namespace:
      discovery:
        namespace:
      server-addr:
      username:
      password:

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

com:
  cloud:
    redis:
      standalone:
        address:
        password:
        user-name:
